### ISSUE TITLE
Laravel 9 Support

### ISSUE THREAD

**Issue by nessimabadi** [asantibanez/livewire-status-board#11]
Hi,

Is there any plan to support Laravel 9?

**Comment by 17Pixelz** [comment]
Any updates here?

**Comment by heloufir** [comment]
Do you guys found any workaround, because I think the PR will not be merged soon.

**Comment by moleculech** [comment]
Do it as discribed here:

https://github.com/asantibanez/livewire-calendar/issues/52

Maybe create the fork yourself
