### ISSUE TITLE
Remove jQuery dependency

### ISSUE THREAD

**Issue by messerli90** [asantibanez/livewire-status-board#2]
I noticed the only place jQuery is being used is `resources/views/sortable.blade.php`

```js
...
const fromOrderedIds = $(evt.from).children().map((index, child) => child.id).get();

const toOrderedIds = $(evt.to).children().map((index, child) => child.id).get();
```

I updated this locally to make it work without jQuery:

```js
const fromOrderedIds = [].slice.call(evt.from.children).map((child, i) => child.id);
```

I can make a PR if you'd like

**Comment by asantibanez** [comment]
Hey @messerli90 

That's interesting. Looking forward to the PR! 👍

**Comment by usernotnull** [comment]
+1

**Comment by asantibanez** [comment]
Thanks @messerli90 for the suggested enhancement. I've just added it to v2.0.0. 👍
