### ISSUE TITLE
getting issue while installation

### ISSUE THREAD

**Issue by RohitRD31** [asantibanez/livewire-status-board#4]
Hello sir getting this issue while installation
 Problem 1
    - Can only install one of: livewire/livewire[1.x-dev, v2.2.7].
    - Can only install one of: livewire/livewire[v2.2.7, 1.x-dev].
    - Can only install one of: livewire/livewire[1.x-dev, v2.2.7].
    - asantibanez/livewire-status-board 1.0.0 requires livewire/livewire ^1.1 -> satisfiable by livewire/livewire[1.x-dev].
    - Installation request for asantibanez/livewire-status-board ^1.0 -> satisfiable by asantibanez/livewire-status-board[1.0.0].
    - Installation request for livewire/livewire (locked at v2.2.7, required as ^2.0) -> satisfiable by livewire/livewire[v2.2.7].

Laravel version 8.6.0
Livewire version 2.2.7

**Comment by aanorbel** [comment]
Hello, @RohitRD31  this is resolved by #3 . I faced the issues earlier and decided to make a pull request. 
I am hoping it gets merged soon

**Comment by RohitRD31** [comment]
Thanks alot

**Comment by RohitRD31** [comment]
hello @aanorbel  can you please tell me what can I do to use this packag untill admin decide to pull merge

**Comment by asantibanez** [comment]
Ready @RohitRD31 . Give it a try now. Let me know your experience with the package. 👍

**Comment by RohitRD31** [comment]
I still having same issue

**Comment by aanorbel** [comment]
@asantibanez  please can you make a new release to https://packagist.org/?

@RohitRD31 for the meantime you can do this to install the dependency:

```json
{
....
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/asantibanez/livewire-status-boardgit"
        }
    ]
}
```

You may need to clear your composer cache `composer clear-cache` if it doesn't work on first try.

**Comment by RohitRD31** [comment]
I guess I have to find alternative or have to code it my self

Could not fetch https://api.github.com/repos/asantibanez/livewire-status-board, please review your configured GitHub OAuth token or enter a new one to access private repos
Head to https://github.com/settings/tokens/new?scopes=repo&description=Composer+on+DESKTOP-H72GHA2+2020-10-03+1528
to retrieve a token. It will be stored in "C:/Users/JD/AppData/Roaming/Composer/auth.json" for future use by Composer.
Token (hidden):

Created token still no luck.

Maybe I should give up on this package

**Comment by aanorbel** [comment]
Hello, @RohitRD31  please try this as a temporal fix before the repository owner can publish the latest version.

```bash
composer require aanorbel/livewire-status-board
```


Installation logs

```bash
 ~/Desktop/test>>  composer -v require aanorbel/livewire-status-board                                                                            

Using version ^1.0 for aanorbel/livewire-status-board
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Dependency resolution completed in 1.129 seconds
Analyzed 25934 packages to resolve dependencies
Analyzed 1117320 rules to resolve dependencies
Dependency resolution completed in 0.001 seconds
Package operations: 2 installs, 0 updates, 0 removals
Installs: livewire/livewire:v2.2.9, aanorbel/livewire-status-board:1.0.1
  - Installing livewire/livewire (v2.2.9): Downloading (100%)
 Extracting archive  - Installing aanorbel/livewire-status-board (1.0.1): Downloading (100%)
 Extracting archiveWriting lock file
Generating optimized autoload files
> post-autoload-dump: Illuminate\Foundation\ComposerScripts::postAutoloadDump
> post-autoload-dump: @php artisan package:discover --ansi
Discovered Package: aanorbel/livewire-status-board
Discovered Package: facade/ignition
Discovered Package: fideloper/proxy
Discovered Package: fruitcake/laravel-cors
Discovered Package: laravel/tinker
Discovered Package: livewire/livewire
Discovered Package: nesbot/carbon
Discovered Package: nunomaduro/collision
Package manifest generated successfully.
74 packages you are using are looking for funding.
Use the `composer fund` command to find out more!

```

Let me know if there is any problem.
