### ISSUE TITLE
Get model instead of id in callbacks

### ISSUE THREAD

**Issue by Ahrengot** [asantibanez/livewire-status-board#5]
Hey there, thanks for a great package!

Would it be possible to have model binding in the callsbacks? Livewire supports this, but I'm not sure if this is possible when overwriting methods from LivewireStatusBoard in our own custom implementations.

I need to do a redirect that requires some data from a related model, and right now I have to first load that model with a findOrFail. It would be nice if I could just do this

```PHP
class CustomStatusBoard extends LivewireStatusBoard
{
    public function onRecordClick(MyModel $model)
    {
        $this->redirect(route('custom.show', ['parent' => $model->parent, 'model' => $model]));
    }
}
```

**Comment by aanorbel** [comment]
Hello @Ahrengot ,

To be able to have that, you can override the [record.blade.php](https://github.com/asantibanez/livewire-status-board/blob/master/resources/views/record.blade.php) especially at https://github.com/asantibanez/livewire-status-board/blob/09ea36f452eb218bc80155f5a5780bb5de5d334e/resources/views/record.blade.php#L6

Good luck and feel free to contact me if you are stuck.

**Comment by Ahrengot** [comment]
Thank you!
